config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get :search, to: 'home#search'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }  

  resources :users, only: [] do 
    scope module: :users do 
      resources :profile, only: [] do 
        collection do 
          get :overview 
          get :posts 
          get :comments 
          get :saved 
          get :upvoted 
          get :downvoted
        end
      end

      collection do 
        resources :interests, only: %i[create] do 
          get :posts 
          get :communities
        end

        resources :settings, only: [] do 
          collection do 
            get :account
            get :profile
            get :subscription
            post :update_info
          end
        end

        resources :chatrooms, only: %i[index show create] do 
          scope module: :chatrooms do 
            resources :messages, only: %i[create]
            resources :users, only: %i[create]
          end
      
          collection do 
            resources :users, only: [] do 
              get :direct_chatroom, to: 'chatrooms#show_direct'
            end
          end
        end

        resources :subscriptions, only: %i[new create] do 
          collection do 
            get :success
          end
        end

        resources :communities, only: %i[create show edit update] do 
          scope module: :communities do 
            resources :users, only: %i[create] 
            resources :interests, only: %i[create]
      
            get 'posts/:type/new', to: 'posts#new', as: 'posts_new'
            post 'posts/:type', to: 'posts#create', as: 'posts'
      
            resources :community_users, only: [] do 
              post :toggle_status
            end
      
            collection do 
              resources :tags, only: %i[destroy]
            end
          end
      
          get :blocked, to: 'communities#blocked'
        end 

        resources :posts, only: %i[show new create destroy] do 
          scope module: :posts do  
            resources :comments, only: %i[create]
            resources :poll_votes, only: %i[create]
      
            collection do 
              resources :votes, only: %i[create]
            end  
          end

          member do 
            post :toggle_status
            get :toggle_pinned
            get :save, to: 'posts#bookmark'
          end
        end
      end
    end
  end
 
  namespace :admin do 
    resources :communities, only: %i[index] 
  end

  get 'moderator/:id/:status/:type', to: 'moderators#moderate_resources', as: 'moderator_resources'

  namespace :api do 
    namespace :v1 do 
      resources :webhooks, only: %i[create]
    end
  end
end

app/controllers/users/chatrooms/chatrooms_base_controller.rb
# frozen_string_literal: true

module Users
  module Chatrooms
    class ChatroomsBaseController < ApplicationController
      before_action :authenticate_user!
    end
  end
end

app/controllers/users/chatrooms/messages_controller.rb
# frozen_string_literal: true

module Users
  module Chatrooms
    class MessagesController < ChatroomsBaseController
      def create
        message = Message.create(message_params)
        message.chatroom.update(newest_message_sent_at: message.created_at)
      end

      private

      def message_params
        params.require(:message).permit(:content, :user_id, :chatroom_id)
      end
    end
  end
end

app/controllers/users/chatrooms/users_controller.rb
# frozen_string_literal: true

module Users
  module Chatrooms
    class UsersController < ChatroomsBaseController
      def create
        chatroom = Chatroom.find(params[:id])
        chatroom.add_users(params[:user_id])
        flash[:notice] = 'New members added!'
        redirect_to chatroom_path(chatroom)
      end
    end
  end
end

app/controllers/users/chatrooms_controller.rb
# frozen_string_literal: true

module Users
  class ChatroomsController < UsersBaseController
    skip_before_action :prepare_query
    skip_before_action :populate_communities
    skip_before_action :prepare_notifications
    skip_before_action :prepare_interests_all
    before_action :prepare_chatrooms

    def index; end

    def show
      @chatroom = Chatroom.includes(messages: [:user]).find(params[:id])

      if @chatroom.room_type == 'group'
        render template: 'chatrooms/show_group'
      else
        render template: 'chatrooms/show_direct'
      end
    end

    def show_direct
      @direct_user = User.find(params[:user_id])

      @direct_chatroom = Chatroom.includes(messages: [:user]).find_or_create_direct_chatroom(current_user, @direct_user)

      redirect_to chatroom_path(@direct_chatroom)
    end

    def create
      chatroom = Chatroom.new(chatroom_params.merge(users: [current_user], room_type: 'group'))

      if chatroom.save
        flash[:notice] = 'Chatroom was successfully created!'
        redirect_to chatroom_path(chatroom)
      else
        flash[:alert] = "Oops, something's wrong, can't create chatroom..."
        redirect_to chatrooms_path
      end
    end

    private

    def prepare_chatrooms
      @group_chatrooms = current_user.chatrooms.by_type('group').order(newest_message_sent_at: :desc)
      @direct_chatrooms = current_user.chatrooms.by_type('direct').order(newest_message_sent_at: :desc)
      @users = User.where.not(id: current_user)
    end

    def chatroom_params
      params.require(:chatroom).permit(:name)
    end
  end
end

app/controllers/users/communities/communities_base_controller.rb
# frozen_string_literal: true

module Users
  module Communities
    class CommunitiesBaseController < ApplicationController
      before_action :prepare_community
      before_action :authenticate_user!

      def prepare_community
        community_id = params[:id] || params[:community_id]
        @community = Community.find(community_id)
      end
    end
  end
end

app/controllers/users/communities/community_users_controller.rb
# frozen_string_literal: true

module Users
  module Communtiies
    class CommunityUsersController < CommunitiesBaseController
      skip_before_action :prepare_community

      def toggle_status
        @community_user = CommunityUser.find(params[:id])

        if @community_user.status == 'moderating' || community_user_status_params[:status] != @community_user.status
          @community_user.update(community_user_status_params)
          flash[:notice] = "User #{@community_user.status}!"
        else
          @community_user.update(status: 'moderating')
          flash[:notice] = "User's status revert to moderating"
        end

        redirect_back(fallback_location: post_path(@community_user))
      end

      private

      def community_user_status_params
        params.require(:community_user).permit(:status)
      end
    end
  end
end

app/controllers/users/communities/interests_controller.rb
# frozen_string_literal: true

module Users
  module Communities
    class InterestsController < CommunitiesBaseController
      def create
        @community.add_interests(params[:interests_id])
        flash[:notice] = "Community's topics updated!"

        redirect_to community_path(@community)
      end
    end
  end
end

app/controllers/users/communities/posts_controller.rb
# frozen_string_literal: true

module Users
  module Communities
    class PostsController < CommunitiesBaseController
      def new
        @post = Post.new(post_type: params[:type])
        2.times { @post.poll_options.build } if params[:type] == 'poll'
      end

      def create
        @post = current_user.posts.build(post_params.merge(post_type: params[:type], community_id: params[:community_id], status: 'moderating'))

        if @post.save
          flash[:success] = 'Post was successfully created, waiting for approve from moderators!'
          redirect_to post_path(@post)
        else
          flash[:alert] = "Something's wrong, post was not created."
          redirect_back(fallback_location: new_post_path(community_id: params[:community_id], type: params[:type]))
        end
      end

      private

      def post_params
        params.require(:post).permit(:title, :content, poll_options_attributes: [:name])
      end
    end
  end
end

app/controllers/users/communities/tags_controller.rb
# frozen_string_literal: true

module Users
  module Communities
    class TagsController < CommunitiesBaseController
      skip_before_action :prepare_community

      def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy

        flash[:notice] = "Community's topic removed"
        redirect_to community_path(@tag.taggable)
      end
    end
  end
end

app/controllers/users/communities/users_controller.rb
# frozen_string_literal: true

module Users
  module Communities
    class UsersController < CommunitiesBaseController
      def create
        if @community.add_user(current_user, 'member')
          flash[:notice] = 'Join request sent, please wait for review from moderator!'
        else
          flash[:alert] =
            'Your request is still being processed. If this take too longs, please contact moderators of this community'
        end

        redirect_to community_path(@community)
      end
    end
  end
end

app/controllers/users/communities_controller.rb
# frozen_string_literal: true

module Users
  class CommunitiesController < UsersBaseController
    before_action :authenticate_user!, only: %i[create]
    before_action :prepare_community, only: %i[show blocked edit update]

    def show
      redirect_to community_blocked_path(@community) and return unless (user_signed_in? && @community.can_be_show?(current_user)) || (!user_signed_in? && @community.community_type == 'public')

      @pinned_posts = @community.posts_by_status('approved').where(pinned: true)

      @pagy, @posts = pagy(@community.posts_by_status('approved').where(pinned: false).includes(%i[votes user rich_text_content]).order(created_at: :desc))

      @community_interests = @community.interests

      respond_to do |format|
        format.html
        format.json do
          render json: {
            nextPosts: render_to_string(
              partial: 'shared/posts_preview',
              locals: { posts: @posts, need_icon: false, display_pin: true },
              format: [:html]
            ),
            pagination: view_context.pagy_nav(@pagy)
          }
        end
      end
    end

    def create
      @community = Community.new(community_params)

      if @community.save
        @community.add_user(current_user, 'moderator')
        flash[:success] = 'Community was successfully created!'
        redirect_to community_path(@community)
      else
        flash[:alert] = "Can't create community, name was aready taken"
        redirect_back(fallback_location: root_path)
      end
    end

    def blocked; end

    def edit; end

    def update
      @community.update(community_update_params)
      flash[:notice] = 'Community settings updated!'
      redirect_to edit_community_path(@community)
    end

    private

    def prepare_community
      community_id = params[:id] || params[:community_id]
      @community = Community.find(community_id)
    end

    def community_params
      params.require(:community).permit(:name, :community_type)
    end

    def community_update_params
      params.require(:community).permit(:community_icon)
    end
  end
end

app/controllers/users/interests_controller.rb
# frozen_string_literal: true

module Users
  class InterestsController < UsersBaseController
    before_action :prepare_interest

    def create
      current_user.add_interests(params[:interests_id])
      flash[:notice] = 'Your interests has been updated!'

      redirect_to root_path
    end

    def posts
      @pagy, @posts = pagy(Post.by_status('approved').where(community_id: @interest.communities).order(created_at: :desc))

      respond_to do |format|
        format.html
        format.json do
          render json: {
            nextPosts: render_to_string(
              partial: 'shared/posts_preview',
              locals: { posts: @posts, need_icon: true, display_pin: false },
              format: [:html]
            ),
            pagination: view_context.pagy_nav(@pagy)
          }
        end
      end
    end

    def communities
      @communities = @interest.communities
    end

    private

    def prepare_interest
      @interest = Interest.find(params[:interest_id])
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      process_oauth('Google')
    end

    def facebook
      process_oauth('Facebook')
    end

    private

    def process_oauth(provider)
      @user = User.from_omniauth(auth)

      if @user.persisted?
        sign_out_all_scopes
        flash[:success] = t 'devise.omniauth_callbacks.success', kind: provider
        sign_in_and_redirect @user, event: :authentication
      else
        flash[:alert] =
          t 'devise.omniauth_callbacks.failure', kind: provider, reason: "#{auth.info.email} is not authorized"
        session["devise.#{provider.downcase}_data"] = request.env['omniauth.auth'].except('extra')
        redirect_to new_user_registration_url
      end
    end

    def auth
      @auth ||= request.env['omniauth.auth']
    end
  end
end

app/controllers/users/posts/comments_controller.rb
# frozen_string_literal: true

module Users
  module Posts
    class CommentsController < PostsBaseController
      def create
        @comment = current_user.comments.build(comment_params)
        @post = @comment.post

        return unless @comment.save

        flash[:success] = 'Comment was successfully created!'

        unless current_user.id == @post.user.id
          ActionCable.server.broadcast("notification_#{@post.user.id}",
                                       {
                                         message: "u/#{current_user.full_name} replied to your post in r/#{@post.community.name}", post_id: @post.id
                                       })
        end

        redirect_to post_path(@post)
      end

      private

      def comment_params
        params.require(:comment).permit(:content, :parent_id).merge(post_id: params[:post_id])
      end
    end
  end
end

app/controllers/users/posts/poll_votes_controller.rb
# frozen_string_literal: true

module Users
  module Posts
    class PollVotesController < PostsBaseController
      before_action :prepare_post

      def create
        @user_poll = UserPoll.new(user_poll_params.merge(user_id: current_user.id))

        if @user_poll.save
          flash[:notice] = 'Poll voted!'
        else
          flash[:alert] = "Something's wrong, can't vote poll!"
        end

        redirect_back(fallback_location: post_path(@post))
      end

      private

      def prepare_post
        post_id = params[:id] || params[:post_id]
        @post = Post.find(post_id)
      end

      def user_poll_params
        params.require(:user_poll).permit(:poll_option_id)
      end
    end
  end
end

app/controllers/users/posts/posts_base_controller.rb
# frozen_string_literal: true

module Users
  module Posts
    class PostsBaseController < ApplicationController
      before_action :authenticate_user!
    end
  end
end

app/controllers/users/posts/votes_controller.rb
# frozen_string_literal: true

module Users
  module Posts
    class VotesController < PostsBaseController
      before_action :authenticate_user!

      def create
        voteable_type = params[:vote][:voteable_type]
        voteable_id = params[:vote][:voteable_id].to_i
        value = params[:vote][:value].to_i

        @vote = current_user.votes.find_by(voteable_type: voteable_type, voteable_id: voteable_id)

        if @vote
          if @vote.value == value
            @vote.destroy
          else
            @vote.update(vote_params)
          end
        else
          @vote = current_user.votes.build(vote_params)
          @vote.save
        end
      end

      private

      def vote_params
        params.require(:vote).permit(:value, :voteable_type, :voteable_id)
      end
    end
  end
end

app/controllers/users/profile_controller.rb
# frozen_string_literal: true

module Users
  class ProfileController < UsersBaseController
    before_action :prepare_user_profile
    before_action :authenticate_user!, only: %i[saved upvoted downvoted]

    def overview
      @posts = @user.posts.includes(:votes, :rich_text_content, :community).where(status: 'approved')
    end

    def posts
      @posts = if user_signed_in? && @user == current_user
                 @user.posts.includes(:votes, :rich_text_content, :community)
               else
                 @user.posts.includes(:votes, :rich_text_content, :community).where(status: 'approved')
               end
    end

    def comments
      @comments = @user.comments.includes(post: [:community]).order(created_at: :desc)
    end

    def saved
      @saved_posts = @user.saved_posts.where(status: 'approved')
    end

    def upvoted
      set_posts_on_vote(:upvote)
    end

    def downvoted
      set_posts_on_vote(:downvote)
    end

    private

    def prepare_user_profile
      @user = User.find(params[:user_id])
    end

    def set_posts_on_vote(value)
      votes_id = @user.votes.where(value: value, voteable_type: 'Post').pluck(:voteable_id)
      @posts = Post.where(id: votes_id)
    end
  end
end

app/views/users/settings/account.slim
= render partial: "shared/navbar", locals: {community: nil}

.w-screen.min-h-screen.bg-white.pt-28 [class="dark:bg-gray-700" data-controller="modal"]
  .mx-auto.flex.flex-col.gap-10 class="w-3/4"
    h1.text-xl.font-bold class="dark:text-white"
      | User settings
    
    = render partial: "shared/settings_links", locals: {current_name: "Account"}

    h1.text-2xl.font-bold class="dark:text-white"
      | Account settings
    h2.text-gray-500.text-sm.font-bold.font-sans class="dark:text-gray-300"
      | ACCOUNT PREFERENCE
    
    .flex.justify-between.items-center class="w-1/2"
      .flex.flex-col
        .span.text-lg.font-bold class="dark:text-white"
          | Email address 
        .span.text-sm.text-gray-500 class="dark:text-gray-300"
          = current_user.email
      button#changeEmail-open.px-5.py-2.font-bold.font-sans.text-blue-500.border.border-blue-500.rounded-full [class="dark:border-white dark:text-white" data-action="click->modal#showModal"]
        | Change
    
    .flex.justify-between.items-center class="w-1/2"
      .flex.flex-col
        .span.text-lg.font-bold class="dark:text-white"
          | Change password 
        .span.text-sm.text-gray-500 class="dark:text-gray-300"
          | Password must be at least 8 characters long
      button#changePassword-open.px-5.py-2.font-bold.font-sans.text-blue-500.border.border-blue-500.rounded-full [class="dark:border-white dark:text-white" data-action="click->modal#showModal"]
        | Change

    .flex.flex-col.mt-8
      h2.text-gray-500.text-sm.font-bold.font-sans class="dark:text-gray-300"
        | DELETE ACCOUNT

      .flex.justify-between.items-center class="w-1/2"
        .
        button#deleteAccount-open.px-5.py-2.font-bold.font-sans.text-red-500.rounded-full.text-sm.flex.gap-2.items-center [data-action="click->modal#showModal"]
          i class="fa-solid fa-trash pointer-events-none"
          span.pointer-events-none
            | DELETE_ACCOUNT
  
  = render partial: "shared/change_email_modal"
  = render partial: "shared/change_password_modal"
  = render partial: "shared/delete_account_modal"

app/views/users/settings/profile.slim
= render partial: "shared/navbar", locals: {community: nil}

.w-screen.min-h-screen.bg-white.py-28 [class="dark:bg-gray-700"]
  .mx-auto.flex.flex-col.gap-10 class="w-3/4"
    h1.text-xl.font-bold class="dark:text-white"
      | Customize profile
    = render partial: "shared/settings_links", locals: {current_name: "Profile"}

    h2.text-gray-500.text-sm.font-bold.font-sans class="dark:text-gray-300"
      | PROFILE INFORMATION
    
    .flex.flex-col.gap-2
      strong.text-xl class="dark:text-white"
        | Display name (optional)
      p.text-gray-500 class="dark:text-gray-300"
        | Set a display name.

      = form_with model: User.new, url: update_info_settings_path, method: :post, class: "flex flex-col gap-4" do |f|
        = f.text_field :full_name, placeholder: "Display name (optional)", class: "w-1/2 mt-2 p-3 rounded-lg text-lg outline-none focus:ring-2 focus:ring-black dark:bg-gray-700 dark:text-white dark:focus:ring-white"
        
        .flex
          = f.submit "Change", class: "bg-blue-500 font-sans font-bold text-white py-2 px-6 rounded-full dark:bg-white dark:text-gray-700"
      
    .flex.flex-col.gap-2
      strong.text-xl class="dark:text-white"
        | About (optional)
      p.text-gray-500 class="dark:text-gray-300"
        | A brief description of yourself shown on your profile.
      
      = form_with model: User.new, url: update_info_settings_path, method: :post, class: "flex flex-col gap-4" do |f|
        = f.text_area :description, placeholder: "About (optional)", class: "w-1/2 mt-2 p-3 rounded-lg text-lg outline-none focus:ring-2 focus:ring-black dark:bg-gray-700 dark:text-white dark:focus:ring-white"
        
        .flex
          = f.submit "Change", class: "bg-blue-500 font-sans font-bold text-white py-2 px-6 rounded-full dark:bg-white dark:text-gray-700"
    
    .flex.flex-col.gap-2
      strong.text-xl class="dark:text-white"
        | Avatar
      
      .h-40.w-40.rounded-lg.bg-gray-500.overflow-hidden
        - if current_user.current_avatar
          = image_tag current_user.current_avatar, class: "w-full h-full object-cover"

      = form_with model: User.new, url: update_info_settings_path, method: :post, class: "mt-2 flex flex-col gap-4" do |f|
        = f.file_field :avatar, class: "dark:text-white"
        .flex
          = f.submit "Change", class: "bg-blue-500 font-sans font-bold text-white py-2 px-6 rounded-full dark:bg-white dark:text-gray-700"

app/views/users/settings/subscriptions.slim
= render partial: "shared/navbar", locals: {community: nil}

.w-screen.min-h-screen.bg-white.pt-28 [class="dark:bg-gray-700"]
  .mx-auto.flex.flex-col.gap-10 class="w-3/4"
    h1.text-xl.font-bold class="dark:text-white"
      | User settings
    = render partial: "shared/settings_links", locals: {current_name: "Subscriptions"}
    h1.text-2xl.font-bold class="dark:text-white"
      | Reddit Clone Premium
    
    p.text-gray-500 class="dark:text-gray-300"
      | Reddit Clone Premium is a subscription membership that upgrades your account with extra features. 
    
    h2.text-gray-500.text-sm.font-bold.font-sans class="dark:text-gray-300"
      | SUBSCRIPTION STATUS
    
    p.text-gray-500 class="dark:text-gray-300"
      | Get Reddit Clone Premium and help support Vance.
    
    .flex.justify-between.text-blue-500.text-xl class="w-1/2"
      = link_to new_subscription_path do 
        p.font-bold.flex.gap-2.items-center class="dark:text-white"
          | Get Premium
          i class="fa-solid fa-share-from-square"
      
      = link_to new_subscription_path do 
        p.text-2xl class="dark:text-white"
          i class="fa-solid fa-arrow-right"