config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get :search, to: 'home#search'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }  

  resources :users, only: [] do 
    scope module: :users do 
      resources :profile, only: [] do 
        collection do 
          get :overview 
          get :posts 
          get :comments 
          get :saved 
          get :upvoted 
          get :downvoted
        end
      end

      collection do 
        resources :interests, only: %i[create] do 
          get :posts 
          get :communities
        end

        resources :settings, only: [] do 
          collection do 
            get :account
            get :profile
            get :subscription
            post :update_info
          end
        end

        resources :chatrooms, only: %i[index show create] do 
          scope module: :chatrooms do 
            resources :messages, only: %i[create]
            resources :users, only: %i[create]
          end
      
          collection do 
            resources :users, only: [] do 
              get :direct_chatroom, to: 'chatrooms#show_direct'
            end
          end
        end

        resources :subscriptions, only: %i[new create] do 
          collection do 
            get :success
          end
        end

        resources :communities, only: %i[create show edit update] do 
          scope module: :communities do 
            resources :users, only: %i[create] 
            resources :interests, only: %i[create]
      
            get 'posts/:type/new', to: 'posts#new', as: 'posts_new'
            post 'posts/:type', to: 'posts#create', as: 'posts'
      
            resources :community_users, only: [] do 
              post :toggle_status
            end
      
            collection do 
              resources :tags, only: %i[destroy]
            end
          end
      
          get :blocked, to: 'communities#blocked'
        end 

        resources :posts, only: %i[show new create destroy] do 
          scope module: :posts do  
            resources :comments, only: %i[create]
            resources :poll_votes, only: %i[create]
      
            collection do 
              resources :votes, only: %i[create]
            end  
          end

          member do 
            post :toggle_status
            get :toggle_pinned
            get :save, to: 'posts#bookmark'
          end
        end
      end
    end
  end
 
  namespace :admin do 
    resources :communities, only: %i[index] 
  end

  get 'moderator/:id/:status/:type', to: 'moderators#moderate_resources', as: 'moderator_resources'

  namespace :api do 
    namespace :v1 do 
      resources :webhooks, only: %i[create]
    end
  end
end

app/models/community.rb
# frozen_string_literal: true

class Community < ApplicationRecord
  extend Enumerize
  resourcify
  validates :name, presence: true, length: { maximum: 21 }, uniqueness: true
  validates :community_type, presence: true
  enumerize :community_type, in: %i[public private]

  has_many :community_users, dependent: :destroy
  has_many :users, through: :community_users
  has_many :posts, dependent: :destroy
  has_many :tags, as: :taggable, dependent: :destroy
  has_many :interests, through: :tags
  has_one_attached :community_icon

  scope :by_type, ->(type) { where(community_type: type) }

  def add_user(user, role)
    return if user_joined?(user)

    CommunityUser.create(community_id: id, user_id: user.id, status: role == 'moderator' ? 'approved' : 'moderating')
    user.add_role role.to_sym, self
  end

  def add_interests(interest_ids)
    interest_ids.each do |interest_id|
      Tag.find_or_create_by(taggable_type: 'Community', taggable_id: id, interest_id: interest_id)
    end
  end

  def user_joined?(user)
    users.find_by(id: user.id)
  end

  def posts_by_status(status)
    posts.where(status: status)
  end

  def can_be_show?(user)
    return false if community_users.find_by(user_id: user.id, status: 'rejected')

    community_type == 'public' || user.has_role?(:admin) || (community_type == 'private' && community_users.find_by(
      user_id: user.id, status: 'approved'
    ))
  end

  def moderators
    User.joins(:roles).where("roles.name": 'moderator', "roles.resource_type": 'Community', "roles.resource_id": id)
  end
end

app/controllers/admins/communities_controller.rb
# frozen_string_literal: true

module Admins
  class CommunitiesController < AdminsBaseController
    def index
      @communities = Community.all
    end
  end
end

app/controllers/users/communities/communities_base_controller.rb
# frozen_string_literal: true

module Users
  module Communities
    class CommunitiesBaseController < ApplicationController
      before_action :prepare_community
      before_action :authenticate_user!

      def prepare_community
        community_id = params[:id] || params[:community_id]
        @community = Community.find(community_id)
      end
    end
  end
end

app/controllers/users/communities/community_users_controller.rb
# frozen_string_literal: true

module Users
  module Communtiies
    class CommunityUsersController < CommunitiesBaseController
      skip_before_action :prepare_community

      def toggle_status
        @community_user = CommunityUser.find(params[:id])

        if @community_user.status == 'moderating' || community_user_status_params[:status] != @community_user.status
          @community_user.update(community_user_status_params)
          flash[:notice] = "User #{@community_user.status}!"
        else
          @community_user.update(status: 'moderating')
          flash[:notice] = "User's status revert to moderating"
        end

        redirect_back(fallback_location: post_path(@community_user))
      end

      private

      def community_user_status_params
        params.require(:community_user).permit(:status)
      end
    end
  end
end

app/controllers/users/communities/interests_controller.rb
# frozen_string_literal: true

module Users
  module Communities
    class InterestsController < CommunitiesBaseController
      def create
        @community.add_interests(params[:interests_id])
        flash[:notice] = "Community's topics updated!"

        redirect_to community_path(@community)
      end
    end
  end
end

app/controllers/users/communities/posts_controller.rb
# frozen_string_literal: true

module Users
  module Communities
    class PostsController < CommunitiesBaseController
      def new
        @post = Post.new(post_type: params[:type])
        2.times { @post.poll_options.build } if params[:type] == 'poll'
      end

      def create
        @post = current_user.posts.build(post_params.merge(post_type: params[:type], community_id: params[:community_id], status: 'moderating'))

        if @post.save
          flash[:success] = 'Post was successfully created, waiting for approve from moderators!'
          redirect_to post_path(@post)
        else
          flash[:alert] = "Something's wrong, post was not created."
          redirect_back(fallback_location: new_post_path(community_id: params[:community_id], type: params[:type]))
        end
      end

      private

      def post_params
        params.require(:post).permit(:title, :content, poll_options_attributes: [:name])
      end
    end
  end
end

app/controllers/users/communities/tags_controller.rb
# frozen_string_literal: true

module Users
  module Communities
    class TagsController < CommunitiesBaseController
      skip_before_action :prepare_community

      def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy

        flash[:notice] = "Community's topic removed"
        redirect_to community_path(@tag.taggable)
      end
    end
  end
end

app/controllers/users/communities/users_controller.rb
# frozen_string_literal: true

module Users
  module Communities
    class UsersController < CommunitiesBaseController
      def create
        if @community.add_user(current_user, 'member')
          flash[:notice] = 'Join request sent, please wait for review from moderator!'
        else
          flash[:alert] =
            'Your request is still being processed. If this take too longs, please contact moderators of this community'
        end

        redirect_to community_path(@community)
      end
    end
  end
end

app/controllers/users/communities_controller.rb
# frozen_string_literal: true

module Users
  class CommunitiesController < UsersBaseController
    before_action :authenticate_user!, only: %i[create]
    before_action :prepare_community, only: %i[show blocked edit update]

    def show
      redirect_to community_blocked_path(@community) and return unless (user_signed_in? && @community.can_be_show?(current_user)) || (!user_signed_in? && @community.community_type == 'public')

      @pinned_posts = @community.posts_by_status('approved').where(pinned: true)

      @pagy, @posts = pagy(@community.posts_by_status('approved').where(pinned: false).includes(%i[votes user rich_text_content]).order(created_at: :desc))

      @community_interests = @community.interests

      respond_to do |format|
        format.html
        format.json do
          render json: {
            nextPosts: render_to_string(
              partial: 'shared/posts_preview',
              locals: { posts: @posts, need_icon: false, display_pin: true },
              format: [:html]
            ),
            pagination: view_context.pagy_nav(@pagy)
          }
        end
      end
    end

    def create
      @community = Community.new(community_params)

      if @community.save
        @community.add_user(current_user, 'moderator')
        flash[:success] = 'Community was successfully created!'
        redirect_to community_path(@community)
      else
        flash[:alert] = "Can't create community, name was aready taken"
        redirect_back(fallback_location: root_path)
      end
    end

    def blocked; end

    def edit; end

    def update
      @community.update(community_update_params)
      flash[:notice] = 'Community settings updated!'
      redirect_to edit_community_path(@community)
    end

    private

    def prepare_community
      community_id = params[:id] || params[:community_id]
      @community = Community.find(community_id)
    end

    def community_params
      params.require(:community).permit(:name, :community_type)
    end

    def community_update_params
      params.require(:community).permit(:community_icon)
    end
  end
end

app/controllers/users/posts/comments_controller.rb
# frozen_string_literal: true

module Users
  module Posts
    class CommentsController < PostsBaseController
      def create
        @comment = current_user.comments.build(comment_params)
        @post = @comment.post

        return unless @comment.save

        flash[:success] = 'Comment was successfully created!'

        unless current_user.id == @post.user.id
          ActionCable.server.broadcast("notification_#{@post.user.id}",
                                       {
                                         message: "u/#{current_user.full_name} replied to your post in r/#{@post.community.name}", post_id: @post.id
                                       })
        end

        redirect_to post_path(@post)
      end

      private

      def comment_params
        params.require(:comment).permit(:content, :parent_id).merge(post_id: params[:post_id])
      end
    end
  end
end

app/controllers/users/posts/poll_votes_controller.rb
# frozen_string_literal: true

module Users
  module Posts
    class PollVotesController < PostsBaseController
      before_action :prepare_post

      def create
        @user_poll = UserPoll.new(user_poll_params.merge(user_id: current_user.id))

        if @user_poll.save
          flash[:notice] = 'Poll voted!'
        else
          flash[:alert] = "Something's wrong, can't vote poll!"
        end

        redirect_back(fallback_location: post_path(@post))
      end

      private

      def prepare_post
        post_id = params[:id] || params[:post_id]
        @post = Post.find(post_id)
      end

      def user_poll_params
        params.require(:user_poll).permit(:poll_option_id)
      end
    end
  end
end

app/controllers/users/posts/posts_base_controller.rb
# frozen_string_literal: true

module Users
  module Posts
    class PostsBaseController < ApplicationController
      before_action :authenticate_user!
    end
  end
end

app/controllers/users/posts/votes_controller.rb
# frozen_string_literal: true

module Users
  module Posts
    class VotesController < PostsBaseController
      before_action :authenticate_user!

      def create
        voteable_type = params[:vote][:voteable_type]
        voteable_id = params[:vote][:voteable_id].to_i
        value = params[:vote][:value].to_i

        @vote = current_user.votes.find_by(voteable_type: voteable_type, voteable_id: voteable_id)

        if @vote
          if @vote.value == value
            @vote.destroy
          else
            @vote.update(vote_params)
          end
        else
          @vote = current_user.votes.build(vote_params)
          @vote.save
        end
      end

      private

      def vote_params
        params.require(:vote).permit(:value, :voteable_type, :voteable_id)
      end
    end
  end
end

app/controllers/users/posts_controller.rb
# frozen_string_literal: true

module Users
  class PostsController < UsersBaseController
    before_action :authenticate_user!, except: %i[show]
    before_action :prepare_post, only: %i[toggle_pinned toggle_status destroy]

    def show
      @post = Post.includes(:community, :user, comments: %i[user votes]).find(params[:id])

      mark_notifications_as_read
    end

    def new
      @post = Post.new
    end

    def create; end

    def destroy
      if @post
        @post.destroy
        redirect_to community_path(@post.community)
      else
        flash[:alert] = "Something wrong, can't delete post"
        redirect_to post_path(@post)
      end
    end

    def bookmark
      post = current_user.saved_posts.find_by(id: params[:id])
      message = ''
      is_saved = true

      if post.nil?
        post = Post.find(params[:id])
        current_user.saved_posts << post
        message = 'Post saved successfully.'
      else
        current_user.saved_posts.delete(post)
        message = 'Post unsaved successfully!'
        is_saved = false
      end

      respond_to do |format|
        format.html
        format.json do
          render json: {
            message: message,
            isSaved: is_saved
          }
        end
      end
    end

    def toggle_pinned
      @post.toggle(:pinned).save

      respond_to do |format|
        format.html
        format.json do
          render json: {
            message: @post.pinned ? 'Post pinned' : 'Pin removed from post',
            isPinned: @post.pinned
          }
        end
      end
    end

    def toggle_status
      if @post.status == 'moderating' || post_status_params[:status] != @post.status
        @post.update(post_status_params)
        flash[:notice] = "Post was #{@post.status}!"
      else
        @post.update(status: 'moderating')
        flash[:notice] = 'Post status changed to moderating'
      end

      redirect_back(fallback_location: post_path(@post))
    end

    private

    def prepare_post
      post_id = params[:id] || params[:post_id]
      @post = Post.find(post_id)
    end

    def mark_notifications_as_read
      @post.notifications_as_post_pg.where(recipient: current_user).mark_as_read!
    end

    def post_status_params
      params.require(:post).permit(:status)
    end
  end
end

app/helpers/communities_helper.rb
# frozen_string_literal: true

module CommunitiesHelper
  def user_status_in_community(user, community)
    community_user = CommunityUser.find_by(community_id: community.id, user_id: user.id)

    if community_user
      case community_user.status
      when 'approved'
        'Joined'
      when 'moderating'
        'Processing'
      when 'rejected'
        'Banned'
      end
    else
      'Join'
    end
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def post_has_images?(post)
    post.content.body.attachments.any? { |a| a.content_type.include?('image') }
  end

  def post_saved?(user = nil, post = nil)
    if user && post
      user.saved_posts.find_by(id: post.id).nil? ? false : true
    else
      false
    end
  end

  def votes_count(post)
    UserPoll.where(poll_option_id: post.poll_options).count
  end

  def option_voted(post)
    return unless user_signed_in? && post.post_type == 'poll'

    current_user.voted_option(post)
  end

  def post_title(post)
    post.title.truncate(60)
  end
end

app/views/users/communities/posts/new.slim
- if user_signed_in? 
  = render partial: "shared/navbar", locals: {community: @community}
- else
  = render partial: "shared/unsigned_navbar"

.min-h-screen.bg-redditGray.pt-28.pb-16 [class="dark:bg-gray-900" data-controller="dropdown"]
  .mx-auto.flex.gap-8 class="w-3/4"
    .flex.flex-col.gap-6 class="w-2/3"
      h1.text-2xl.font-bold class="dark:text-white"
        | Create a post
      .flex.flex-col.gap-3 
        .relative.navbar__dropdown [data-dropdown]
          button.navbar__dropdown-toggle.w-80.py-2.px-4.bg-white.flex.items-center.gap-4.rounded-lg.shadow [class="dark:bg-gray-700 dark:text-white" data-dropdown-button]
            span.h-8.w-8.rounded-full.bg-blue-500.pointer-events-none.overflow-hidden 
              - if @community.community_icon.attached?
                = image_tag @community.community_icon, class: "w-full h-full object-cover"
            span.font-bold.text-lg.pointer-events-none 
              = "r/#{@community.name}"
            i.pointer-events-none class="ml-auto fa-solid fa-chevron-down my-auto"
        
          .absolute.navbar__dropdown-list.w-80.z-50.px-4.py-2.bg-white.max-h-96.overflow-y-auto.rounded-lg class="dark:bg-gray-700 dark:text-white"
            .flex.flex-col.gap-6
              - current_user.communities.each do |community| 
                - unless community.id == @community.id
                  = link_to community_posts_new_path(community)
                    .flex.items-center.gap-4
                      span.h-8.w-8.rounded-full.bg-blue-500.overflow-hidden 
                        - if community.community_icon.attached?
                          = image_tag community.community_icon, class: "w-full h-full object-cover"
                      span.font-bold.text-lg
                        ="/r#{community.name}"

        .w-full.bg-white.shadow.rounded-md class="dark:bg-gray-700 dark:text-white"
          .w-full.flex
            = link_to community_posts_new_path(community_id: @community, type: "post"), class: "w-1/4"
              .flex.flex-col 
                .flex.gap-2.items-center.justify-center.font-sans.font-bold.text-xl.py-3 class="#{@post.post_type == "post" ? "text-blue-500" : "text-gray-500"}"
                  i class="fa-solid fa-file-lines text-2xl"
                  span
                    |Post
            
            = link_to community_posts_new_path(community_id: @community, type: "poll"), class: "w-1/4"
              .flex.flex-col
                .flex.gap-2.items-center.justify-center.font-sans.font-bold.text-xl.py-3 class="#{@post.post_type == "poll" ? "text-blue-500" : "text-gray-500"}"
                  i class="fa-solid fa-square-poll-horizontal"
                  span
                    |Poll    

          = form_with model: @post, url: community_posts_path(@community), class: "text-lg font-sans p-8 flex flex-col gap-6" do |f|
            = f.text_field :title, placeholder: "Title", class: "w-full focus:outline-none focus:ring-1 focus:ring-black py-2 px-6 rounded-md dark:bg-gray-700 dark:text-white dark:focus:ring-white", required: "true"
            = f.rich_text_area :content, class: "border-none focus:outline-none focus:ring-1 focus:ring-black overflow-scroll dark:bg-gray-700 dark:text-white dark:focus:ring-white", placeholder: "Text (optional)"
            
            - if @post.post_type == "poll"
              .flex.w-full.justify-center.gap-8 data-controller="pollOption"
                .flex.flex-col.gap-2 class="w-7/12" data-pollOption-target="optionContainer" data-last-option-id="1"
                  = f.fields_for :poll_options do |pf|
                    .flex.items-center.gap-2 id="optionContainer#{pf.options[:child_index]}"
                      i class="fa-solid fa-bars text-xl text-gray-500"
                      = pf.text_field :name, placeholder: "Option #{pf.options[:child_index] + 1}", class: "w-full py-2 px-4 focus:outline-none focus:ring-1 focus:ring-black rounded-md dark:bg-gray-700 dark:text-white dark:ring-white", required: "required" 
                  
                  .flex.mt-2
                    button.text-blue-500.font-bold type="button" data-action="click->pollOption#addOption"
                      | Add Option
                      
                .flex.flex-col.gap-2 
                  .flex.gap-2.text-base.items-center
                    i class="fa-solid fa-circle-info"
                    span
                      |Tips on Better Polls 
                  .text-sm 
                    | 1. Suggest short clear options  
                  .text-sm 
                    | 2. The more options, the better
                  .text-sm 
                    | 3. Choose the poll duration
                  .text-sm 
                    | 4. Options can't be edited after post creation       

            = f.submit "Post", class: "rounded-full py-2 px-8 bg-blue-500 font-sans font-bold text-white text-lg ml-auto dark:bg-white dark:text-gray-700"
        

    .flex.flex-col.gap-6
      .w-96.flex.flex-col.gap-6
        .w-full.bg-white.rounded-md.shadow.p-6.font-bold.h-96.flex.flex-col.justify-center class="dark:bg-gray-700 dark:text-white"
          h1.text-xl.mb-4.flex.gap-4.items-center
            .span.w-14.h-14
              = svg_pack_tag "reddit-posting-remind"
            .span
              | Posting to Reddit
          ul.flex.flex-col.gap-6.text-lg
            li 
              | 1. Remember the human
            li 
              | 2. Behave like you would in real life 
            li 
              | 3. Look for the original source of content
            li 
              | 4. Search for duplicates before posting
            li 
              | 5. Read the community's rules

      = render partial: "shared/community_sidebar", locals: {community: @community} 