config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get :search, to: 'home#search'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }  

  resources :users, only: [] do 
    scope module: :users do 
      resources :profile, only: [] do 
        collection do 
          get :overview 
          get :posts 
          get :comments 
          get :saved 
          get :upvoted 
          get :downvoted
        end
      end

      collection do 
        resources :interests, only: %i[create] do 
          get :posts 
          get :communities
        end

        resources :settings, only: [] do 
          collection do 
            get :account
            get :profile
            get :subscription
            post :update_info
          end
        end

        resources :chatrooms, only: %i[index show create] do 
          scope module: :chatrooms do 
            resources :messages, only: %i[create]
            resources :users, only: %i[create]
          end
      
          collection do 
            resources :users, only: [] do 
              get :direct_chatroom, to: 'chatrooms#show_direct'
            end
          end
        end

        resources :subscriptions, only: %i[new create] do 
          collection do 
            get :success
          end
        end

        resources :communities, only: %i[create show edit update] do 
          scope module: :communities do 
            resources :users, only: %i[create] 
            resources :interests, only: %i[create]
      
            get 'posts/:type/new', to: 'posts#new', as: 'posts_new'
            post 'posts/:type', to: 'posts#create', as: 'posts'
      
            resources :community_users, only: [] do 
              post :toggle_status
            end
      
            collection do 
              resources :tags, only: %i[destroy]
            end
          end
      
          get :blocked, to: 'communities#blocked'
        end 

        resources :posts, only: %i[show new create destroy] do 
          scope module: :posts do  
            resources :comments, only: %i[create]
            resources :poll_votes, only: %i[create]
      
            collection do 
              resources :votes, only: %i[create]
            end  
          end

          member do 
            post :toggle_status
            get :toggle_pinned
            get :save, to: 'posts#bookmark'
          end
        end
      end
    end
  end
 
  namespace :admin do 
    resources :communities, only: %i[index] 
  end

  get 'moderator/:id/:status/:type', to: 'moderators#moderate_resources', as: 'moderator_resources'

  namespace :api do 
    namespace :v1 do 
      resources :webhooks, only: %i[create]
    end
  end
end

app/views/shared/_add_chatroom_member_modal.slim
#addChatroomMember-modal.fixed.top-0.left-0.w-screen.h-screen.justify-center.items-center [data-modal-target="modal"]
  .fixed.top-0.left-0.w-screen.h-screen.bg-black.opacity-50
  .bg-white.opacity-100.z-50.rounded-xl.shadow-lg.relative.flex.flex-col.p-8 class="w-1/3"
    button#addChatroomMember-close.absolute.top-6.right-6.text-2xl.text-gray-500 [data-action="click->modal#closeModal"]
      i.pointer-events-none class="fa-solid fa-xmark"
    
    .flex.flex-col.gap-8.text-xl 
      h1.font-bold.text-xl.mx-auto
        | Add User
      
      = form_with url: chatroom_users_path(chatroom), method: :post do |f|
        .flex.flex-col.gap-4.text-lg.h-96.pr-4.overflow-auto
          - chatroom.users_outside_chatroom.each do |user|
            .flex.items-center.gap-4
              label.w-full.flex.items-center.gap-4 for="user_id_#{user.id}"
                .w-12.h-12.rounded-full.bg-gray-500.overflow-hidden
                  img.object-cover [src="#{user.avatar_url}"]
                .font-bold
                  = user.full_name
                
                input.ml-auto.w-6.h-6.rounded-lg type="checkbox" name="user_id[]" value="#{user.id}" id="user_id_#{user.id}" 

        .flex.flex-col.mt-6
          = f.submit "Add user", class: "py-2 bg-blue-500 font-sans font-bold text-white rounded-lg"

app/views/shared/_add_interests_modal.slim
.fixed.top-0.left-0.w-screen.h-screen.z-50.flex.justify-center.items-center  [data-controller="remove"]
  .fixed.top-0.left-0.w-screen.h-screen.bg-black.opacity-50
  .bg-white.opacity-100.z-50.rounded-xl.shadow-lg.relative.flex.flex-col.p-16 class="dark:bg-gray-700 dark:text-white"
    button.absolute.top-6.right-6.text-2xl.text-gray-500 [data-action="click->remove#remove"]
      i.pointer-events-none class="fa-solid fa-xmark"

    .w-full.flex.flex-col.gap-4
      strong.text-xl
        | Choose Your Interests
      
      p 
        | Access many interesting contents base on your hobby
      
      = form_with url: interests_path, class: "flex flex-col gap-4", method: :post do |f|
        - Interest.all.each do |interest| 
          .flex.items-center
            label.font-bold.text-blue-500 for="interest_id_#{interest.id}" 
              = interest.name 
            input.ml-auto.w-6.h-6.rounded-lg type="checkbox" name="interests_id[]" value="#{interest.id}" id="interest_id_#{interest.id}"
        
        = f.submit "Add Interests", class: "py-2 px-6 font-sans font-bold rounded-full bg-blue-500 text-white mt-4 mx-auto dark:bg-white dark:text-gray-700"

app/views/shared/_change_email_modal.slim
#changeEmail-modal.fixed.top-0.left-0.w-screen.h-screen.justify-center.items-center [data-modal-target="modal"]
  .fixed.top-0.left-0.w-screen.h-screen.bg-black.opacity-50
  .bg-white.opacity-100.z-50.rounded-xl.shadow-lg.relative.flex.flex-col.p-16 class="dark:bg-gray-700 dark:text-white"
    button#changeEmail-close.absolute.top-6.right-6.text-2xl.text-gray-500 [data-action="click->modal#closeModal"]
      i.pointer-events-none class="fa-solid fa-xmark"
    
    .w-96.flex.flex-col.gap-4.text-xl
      h1.font-bold.text-2xl 
        | Update your email
      
      p 
        | Update your email below. There will be a new verification email sent that you will need to use to verify this new email.

      = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, class: "flex flex-col gap-4 font-sans text-base" }) do |f|
        = f.password_field :current_password, autocomplete: "current-password", placeholder: "CURRENT PASSWORD", required: "required",class: "p-3 rounded-lg dark:bg-gray-700 dark:text-white"
        = f.email_field :email, required: "required", placeholder: "NEW EMAIL", class: "p-3 rounded-lg dark:bg-gray-700 dark:text-white"
        = f.submit "Save email", class: "ml-auto mt-2 px-5 py-3 text-white bg-blue-500 font-bold  rounded-full dark:bg-white dark:text-gray-700"


      

app/views/shared/_change_password_modal.slim
#changePassword-modal.fixed.top-0.left-0.w-screen.h-screen.justify-center.items-center.z-50 [data-modal-target="modal"]
  .fixed.top-0.left-0.w-screen.h-screen.bg-black.opacity-50
  .bg-white.opacity-100.rounded-lg.shadow-2xl.relative.flex.overflow-hidden class="w-1/2 h-5/6 dark:bg-gray-700 dark:text-white"
    button#changePassword-close.absolute.top-6.right-6.text-2xl.text-gray-500 [data-action="click->modal#closeModal"]
      i.pointer-events-none class="fa-solid fa-xmark"
    
    .authentication__left-container-modal.h-full.w-40.bg-black
    .w-full.h-full.flex.flex-col.justify-center.pl-6.gap-8 
      = svg_pack_tag("reddit-icon", class: "w-11 h-11")

      h1.font-bold.text-2xl
        |Update your password

      = form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, class: "flex flex-col gap-8" }) do |f|
        .input__box.relative
          = f.password_field :current_password, class: "w-96 rounded-md border px-3 pb-1 pt-5 font-bold hover:border-gray-400 dark:bg-gray-700 dark:text-white", placeholder: "", required: "required"
          = f.label :current_password, "OLD PASSWORD", class: "absolute font-bold top-3 left-5 text-gray-500 pointer-events-none dark:text-gray-300"
        .input__box.relative
          = f.password_field :password, class: "w-96 rounded-md border px-3 pb-1 pt-5 font-bold hover:border-gray-400 dark:bg-gray-700 dark:text-white", placeholder: "", required: "required", pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*_=+-]).{8,}$"
          = f.label :password, "NEW PASSWORD", class: "absolute font-bold top-3 left-5 text-gray-500 pointer-events-none dark:text-gray-300"
        .input__box.relative
          = f.password_field :password_confirmation, class: "w-96 rounded-md border px-3 pb-1 pt-5 font-bold hover:border-gray-400 dark:bg-gray-700 dark:text-white", placeholder: "", required: "required"
          = f.label :password_confirmation, "CONFIRM NEW PASSWORD", class: "absolute font-bold top-3 left-5 text-gray-500 pointer-events-none dark:text-gray-300"
        .
          = f.submit "Save", class: "bg-blue-500 font-sans font-bold text-white px-16 py-3 rounded-full dark:bg-white dark:text-gray-700"

app/views/shared/_communities_list.slim
.absolute.top-12.-right-4.p-6.bg-white.navbar__dropdown-list.navbar__community-list class="dark:bg-gray-700 dark:text-white"
  .flex.flex-col.gap-4 
    .text-xs.font-bold.text-gray-500
      | MODERATING
    = link_to moderator_resources_path(id: current_user, status: "moderating", type: "posts"), class:"flex text-lg gap-4 items-center" do
      i class="fa-solid fa-lines-leaning"
      p 
        | Mod Queue
    .flex.text-lg.gap-4.items-center
      i class="fa-solid fa-envelope"
      p 
        | Modmail
    
    - if @moderating_communities
      - @moderating_communities.each do |moderating_community| 
        = link_to community_path(moderating_community) do
          .flex.text-lg.gap-4.items-center
            .h-6.w-6.rounded-full.bg-blue-500.overflow-hidden
              - if moderating_community.community_icon.attached?
                = image_tag moderating_community.community_icon, class: "w-full h-full object-cover"
            p 
              = moderating_community.name

    .text-xs.font-bold.text-gray-500
      | YOUR COMMUNITIES
    
    - if @followed_communities
      - @followed_communities.each do |followed_community| 
        = link_to community_path(followed_community) do
          .flex.text-lg.gap-4.items-center
            .h-6.w-6.rounded-full.bg-blue-500.overflow-hidden
              - if followed_community.community_icon.attached?
                = image_tag followed_community.community_icon, class: "w-full h-full object-cover"
            p 
              = followed_community.name

app/views/shared/_navbar.slim
nav.bg-white.py-3.px-8.fixed.top-0.w-screen.flex.items-center.justify-between.z-50 [class="dark:bg-gray-700 dark:text-white" data-controller="dropdown modal darkmode"]
  = link_to root_path do 
    .flex.gap-3
      = svg_pack_tag("reddit-icon", class: "w-11 h-11")
      = svg_pack_tag("reddit-brand", class: "w-20 h-11")

  .relative.flex.items-center.navbar__dropdown [data-dropdown]
    - unless community
      .flex.gap-3.items-center.w-80
        i class="fa-solid fa-house text-2xl"
        p.text-xl.font-bold  
          | Home
    - else 
      .flex.gap-3.items-center.w-80.text-lg
        .h-6.w-6.rounded-full.bg-blue-500.overflow-hidden
          - if community.community_icon.attached?
            = image_tag community.community_icon, class: "w-full h-full object-cover"
        p.font-bold
          = "r/#{community.name}"

    button.navbar__dropdown-toggle [data-dropdown-button]
      i.pointer-events-none class="fa-solid fa-chevron-down my-auto"
    
    = render partial: "shared/communities_list"
  
  = render partial: "shared/search_bar"
  
  .flex.items-center.text-2xl.gap-6
    - if current_user.has_role? :admin
      = link_to admin_communities_path do
        i class="fa-solid fa-building-shield"

    = link_to moderator_resources_path(id: current_user, status: "moderating", type: "posts") do
      i class="fa-solid fa-shield-halved"

    = link_to chatrooms_path, target: :_blank do
      i class="fa-regular fa-comments"

    .relative.navbar__dropdown [data-dropdown]
      button.navbar__dropdown-toggle.relative [data-dropdown-button]
        i.pointer-events-none class="fa-regular fa-bell"
        #notification-icon.absolute.rounded-full.bg-red-600.-right-2.top-0.px-1.text-white.font-sans.font-bold.text-xs.pointer-events-none.flex.justify-center.items-center data-user-id="#{current_user.id}"
          = @unread_count
      
      = render partial: "shared/notifications_dropdown"
    
    - if community 
      = link_to community_posts_new_path(community_id: community, type: "Post") do
        i class="fa-solid fa-plus"
    - else 
      = link_to new_post_path do
        i class="fa-solid fa-plus"
  
  .flex.gap-2
    .w-8.h-8.bg-gray-500.relative.rounded-md
      .rounded-md.w-full.h-full.overflow-hidden
        - if current_user.current_avatar
          = image_tag current_user.current_avatar, class: "w-full h-full object-cover"
      .absolute.-bottom-1.-right-1.w-4.h-4.rounded-full.bg-green-500.border-2.border-white
    .flex.flex-col.justify-center.w-52
      strong.text-lg
        = current_user.full_name
    .relative.navbar__dropdown [data-dropdown]
      button.navbar__dropdown-toggle [data-dropdown-button]
        i.pointer-events-none class="fa-solid fa-chevron-down my-auto"
      = render partial: "shared/user_dropdown"
  
  = render partial: "shared/create_community_modal"
    

app/views/shared/_post_create_link.slim
- if user_signed_in?
  .w-full.p-3.bg-white.rounded-sm.flex.items-center.shadow class="dark:bg-gray-700 text-white"
    .w-12.h-12.rounded-full.bg-gray-500.overflow-hidden
      - if current_user.current_avatar
          = image_tag current_user.current_avatar, class: "w-full h-full object-cover"
    = link_to "Create post", new_post_path, class: "border border-white text-lg text-gray-500 py-3 px-6 rounded-md ml-4 w-3/4 hover:border-blue-500 dark:border-gray-700 dark:hover:border-white"
    .flex.gap-8.items-center.pr-8.ml-auto
      button.text-3xl.text-gray-500
        i class="fa-regular fa-image"
      button.text-2xl.text-gray-500
        i class="fa-solid fa-link"

app/views/shared/_profile_links.slim
.bg-white.flex.justify-center.pt-20 class="dark:bg-gray-700"
  - if user_signed_in? && @user == current_user
    - ["OVERVIEW", "POSTS", "COMMENTS", "SAVED", "UPVOTED", "DOWNVOTED"].each do |link_name|
      = link_to link_name, eval("#{link_name.downcase}_user_profile_index_path(@user)"), class: "text-lg py-4 px-8 font-bold text-lg dark:text-white dark:bg-gray-700 #{link_name == current_name ? "border-b-4 border-blue-500 dark:border-white text-blue-500 dark:text-white" : ""}"
  - else 
    - ["OVERVIEW", "POSTS", "COMMENTS"].each do |link_name|
      = link_to link_name, eval("#{link_name.downcase}_user_profile_index_path(@user)"), class: "text-lg py-4 px-8 font-bold text-lg dark:text-white dark:bg-gray-700 #{link_name == current_name ? "border-b-4 border-blue-500 dark:border-white text-blue-500 dark:text-white" : ""}"

app/views/shared/_search_bar.slim
= search_form_for(@query, url: search_path, method: :get, class: "w-2/5 text-2xl flex gap-3 border items-center px-4 py-3 rounded-full text-gray-500 hover:border-blue-500 dark:bg-gray-600 dark:border-gray-500 dark:hover:border-white", autocomplete: "off") do |f|
  i class="fa-solid fa-magnifying-glass"
  = f.search_field :name_i_cont_any, class: "text-xl text-black w-full focus:outline-none dark:bg-gray-600 dark:text-white"

app/views/shared/_settings_links.slim
.w-full.flex
  - ["Account", "Profile", "Subscription"].each do |link_name|
    = link_to link_name, eval("#{link_name.downcase}_settings_path"), class: "text-lg pb-4 px-8 font-sans font-bold text-lg dark:text-white #{link_name == current_name ? "border-b-4 border-blue-500 dark:border-white" : ""}"

app/views/shared/_share_post_modal.slim
#sharePost-modal.fixed.top-0.left-0.w-screen.h-screen.justify-center.items-center [data-modal-target="modal" data-controller="clipboard" data-clipboard-url-value="#{post_url(post)}"]
  .fixed.top-0.left-0.w-screen.h-screen.bg-black.opacity-50
  .bg-white.opacity-100.z-50.rounded-xl.shadow-lg.relative.flex.flex-col.gap-6.p-8 class="dark:bg-gray-700 dark:text-white" 
    button#sharePost-close.absolute.top-6.right-6.text-2xl.text-gray-500 [data-action="click->modal#closeModal"]
      i.pointer-events-none class="fa-solid fa-xmark"
  
    strong.text-xl
      | Share Post
    
    .flex.px-2.justify-around
      .flex.flex-col.items-center.gap-4
        .w-12.h-12.flex.items-center.justify-center.rounded-full
          i class="fa-solid fa-code text-2xl text-gray-500 dark:text-gray-300"
        span.text-sm
          | Embed
      .flex.flex-col.items-center.gap-4 
        .w-12.h-12.flex.items-center.justify-center.rounded-full.bg-blue-700.text-white class="dark:bg-white dark:text-gray-700"
          i class="fa-brands fa-facebook-f text-3xl"
        span.text-sm 
          | Facebook
      .flex.flex-col.items-center.gap-4 
        .w-12.h-12.flex.items-center.justify-center.rounded-full.bg-blue-500.text-white class="dark:bg-white dark:text-gray-700"
          i class="fa-brands fa-twitter text-3xl"
        span.text-sm
          | Twitter
      
      .flex.flex-col.items-center.gap-4
        .w-12.h-12.flex.items-center.justify-center.rounded-full.bg-gray-500.text-white class="dark:bg-white dark:text-gray-700"
          i class="fa-solid fa-envelope text-3xl"
        span.text-sm
          | Email

    .w-96.py-2.px-3.border.border-gray-300.rounded-lg.flex.justify-between
      .
        = post_url(post).truncate(30)
      button.text-lg.text-blue-500.font-sans.font-bold [class="dark:text-white" data-clipboard-target="clickBtn" data-action="click->clipboard#saveContent"]
        |COPY

app/views/shared/_signup_modal.slim
#signup-modal.fixed.top-0.left-0.w-screen.h-screen.justify-center.items-center [data-modal-target="modal"]
  .fixed.top-0.left-0.w-screen.h-screen.bg-black.opacity-50
  .bg-white.opacity-100.z-50.rounded-xl.shadow-lg.relative.flex.flex-col.p-16 class="dark:bg-gray-700 dark:text-white"
    button#signup-close.absolute.top-6.right-6.text-2xl.text-gray-500 [data-action="click->modal#closeModal"]
      i.pointer-events-none class="fa-solid fa-xmark"
    
    .w-96.flex.flex-col.gap-4.text-xl
      h1.text-2xl.font-bold.mb-4
        | Sign Up
      .flex.flex-col.gap-4
        = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: "border border-gray-300 rounded-full py-3 px-4 relative text-center" do
          .absolute class="top-1/3 left-6"
            = svg_pack_tag "google-icon"
          strong
            | Continue with Google

        = link_to user_facebook_omniauth_authorize_path, method: :post, class: "border border-gray-300 rounded-full py-3 px-4 relative text-center" do
          .absolute class="top-1/3 left-6"
            = svg_pack_tag "facebook-icon"
          strong
            | Continue with Facebook
      
      strong.my-4.mx-auto.text-lg.text-gray-600
        | OR
      
      = form_for(resource, as: resource_name, html: {class: "w-full flex flex-col gap-4"}, url: registration_path(resource_name)) do |f| 
        = render "devise/shared/error_messages", resource: resource
        .input__box.relative
          = f.email_field :email, class: "w-full rounded-full border px-5 pb-1 pt-5 font-bold hover:border-gray-400 dark:bg-gray-600 dark:border-gray-500 dark:hover:border-white", placeholder: ""
          = f.label :email, class: "absolute font-bold top-3 left-5 text-gray-500 dark:text-gray-300"

        em.text-base.text-left
          |Password must contain at least one uppercase character, one number, one special symbol and have minimum length of 8 characters.
        .input__box.relative
          = f.password_field :password, class: "w-full rounded-full border px-5 pb-1 pt-5 font-bold hover:border-gray-400 dark:bg-gray-600 dark:border-gray-500 dark:hover:border-white", placeholder: "", pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*_=+-]).{8,}$"
          = f.label :password, class: "absolute font-bold top-3 left-5 text-gray-500 dark:text-gray-300"
        
        .input__box.relative
          = f.password_field :password_confirmation, class: "w-full rounded-full border px-5 pb-1 pt-5 font-bold hover:border-gray-400 dark:bg-gray-600 dark:border-gray-500 dark:hover:border-white", placeholder: ""
          = f.label :password_confirmation, class: "absolute font-bold top-3 left-5 text-gray-500 dark:text-gray-300"

        = f.submit "Sign Up", class: "w-full mx-auto mt-4 bg-redditOrange text-white rounded-full px-5 py-3 font-bold"
      
      p.text-lg.pl-3
        |Already a redditor? 
        = link_to "Log In", new_session_path(resource_name), class: "text-blue-500 font-bold underline"

app/views/shared/_user_interactive_bar.slim
.w-full.flex.items-center.pb-4.text-gray-500.gap-4.font-sans.pr-14 class="dark:text-gray-300"
  = link_to post_path(post) do
    .flex.gap-2.text-lg.items-center
      i class="fa-regular fa-comment text-2xl"
      strong 
        = format_comments_count(post.comments.count)

  . data-controller="save" data-save-url-value="#{save_post_url(post)}"  
    button.flex.gap-2.text-lg.items-center data-action="click->save#processSave" data-save-target="saveBtn" 
      - if post_saved?(current_user, post)
        i class="fa-solid fa-bookmark text-2xl"
        strong 
          | Unsave
      - else 
        i class="fa-regular fa-bookmark text-2xl"
        strong 
          | Save

  button#sharePost-open.flex.gap-2.text-lg.items-center [data-action="click->modal#showModal"]
    i class="fa-solid fa-share pointer-events-none"
    strong.pointer-events-none
      | Share
  
  - if current_user&.has_role?(:admin) || current_user&.has_role?(:moderator, post.community)
    = form_with model: post, url: toggle_status_post_path(moderator_id: current_user, id: post.id), method: :POST do |f| 
      = f.hidden_field :status, value: "approved"
      - if post.status == "approved"
        button.flex.gap-2.items-center.text-lg.text-green-500 type="submit"
          i class="fa-solid fa-check text-2xl"
          strong
            | Approved
      - else 
        button.flex.gap-2.items-center.text-lg type="submit"
          i class="fa-solid fa-check text-2xl"
          strong
            | Approve

    = form_with model: post, url: toggle_status_post_path(moderator_id: current_user, id: post.id), method: :POST do |f| 
      = f.hidden_field :status, value: "rejected"
      - if post.status == "rejected"
        button.flex.gap-2.items-center.text-lg.text-red-500 type="submit"
          i class="fa-solid fa-x text-xl"
          strong
            | Rejected
      - else 
        button.flex.gap-2.items-center.text-lg type="submit"
          i class="fa-solid fa-x text-xl"
          strong
            | Reject 
    
    . data-controller="pin" data-pin-url-value="#{toggle_pinned_post_url(post)}"
      button.flex.gap-2.items-center.text-lg class="#{"text-green-500" if post.pinned}" data-action="click->pin#processPin" data-pin-target="pinBtn"
        i class="fa-solid fa-thumbtack"
        strong
          = post.pinned ? "Pinned" : "Pin Post"

  - if user_signed_in? && (post.user == current_user || current_user.has_role?(:admin))
    = link_to post_path(post), class: "flex gap-2 text-lg items-center ml-auto", method: :DELETE do
      i class="fa-solid fa-trash text-xl" 
      strong 
        | Delete

app/views/shared/_user_profile_section.slim
.w-96.flex.flex-col.gap-6
  .w-full.rounded-md.shadow.flex.flex-col.bg-white.overflow-hidden class="dark:bg-gray-700 dark:text-white"
    .home__banner.w-full.h-24.relative 
      - if @user.current_avatar
        .absolute.top-16.left-28.w-40.h-40.rounded-full.overflow-hidden 
          = image_tag @user.current_avatar, class: "w-full h-full object-cover"
      - else 
        .absolute.top-12.left-36.w-28
          = image_pack_tag "media/images/reddit_star.png"
    
    .flex.flex-col.gap-4.pb-4.pt-36
      .font-bold.text-center.text-2xl
        = user.full_name
      .px-4.text-lg
        = user.description

    - if user_signed_in? && user.id == current_user.id
      .flex.flex-col.gap-3.my-4.mx-4
        = link_to "New Post", new_post_path, class: "py-2 text-xl font-sans font-bold text-white rounded-full bg-blue-500 text-center dark:bg-white dark:text-gray-700"
  
  - if user_signed_in? && user.id == current_user.id
    .w-full.rounded-md.shadow.flex.flex-col.gap-3.bg-white.overflow-hidden.p-4 class="dark:bg-gray-700 dark:text-white"
      strong.text-lg.font-sans
        |You're a moderator of these communities
      .flex.flex-col.gap-4.mt-2
        - user.moderating_communities.each do |community|
          .flex.items-center.gap-4
            .h-12.w-12.rounded-full.bg-blue-500.overflow-hidden
              - if community.community_icon.attached?
                = image_tag community.community_icon, class: "w-full h-full object-cover"
            .flex.flex-col.font-bold
              span
                = "r/#{community.name}"
              span.text-gray-500 
                = pluralize(community.users.count, 'member') 