config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get :search, to: 'home#search'
  
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }  

  resources :users, only: [] do 
    scope module: :users do 
      resources :profile, only: [] do 
        collection do 
          get :overview 
          get :posts 
          get :comments 
          get :saved 
          get :upvoted 
          get :downvoted
        end
      end

      collection do 
        resources :interests, only: %i[create] do 
          get :posts 
          get :communities
        end

        resources :settings, only: [] do 
          collection do 
            get :account
            get :profile
            get :subscription
            post :update_info
          end
        end

        resources :chatrooms, only: %i[index show create] do 
          scope module: :chatrooms do 
            resources :messages, only: %i[create]
            resources :users, only: %i[create]
          end
      
          collection do 
            resources :users, only: [] do 
              get :direct_chatroom, to: 'chatrooms#show_direct'
            end
          end
        end

        resources :subscriptions, only: %i[new create] do 
          collection do 
            get :success
          end
        end

        resources :communities, only: %i[create show edit update] do 
          scope module: :communities do 
            resources :users, only: %i[create] 
            resources :interests, only: %i[create]
      
            get 'posts/:type/new', to: 'posts#new', as: 'posts_new'
            post 'posts/:type', to: 'posts#create', as: 'posts'
      
            resources :community_users, only: [] do 
              post :toggle_status
            end
      
            collection do 
              resources :tags, only: %i[destroy]
            end
          end
      
          get :blocked, to: 'communities#blocked'
        end 

        resources :posts, only: %i[show new create destroy] do 
          scope module: :posts do  
            resources :comments, only: %i[create]
            resources :poll_votes, only: %i[create]
      
            collection do 
              resources :votes, only: %i[create]
            end  
          end

          member do 
            post :toggle_status
            get :toggle_pinned
            get :save, to: 'posts#bookmark'
          end
        end
      end
    end
  end
 
  namespace :admin do 
    resources :communities, only: %i[index] 
  end

  get 'moderator/:id/:status/:type', to: 'moderators#moderate_resources', as: 'moderator_resources'

  namespace :api do 
    namespace :v1 do 
      resources :webhooks, only: %i[create]
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @posts = nil
    if user_signed_in?
      private_communities = current_user.communities.by_type('private')

      @posts = Post.joins(:community).where(status: 'approved', "communities.community_type": 'public').or(Post.joins(:community).where(status: 'approved', community: private_communities))
    else
      @posts = Post.joins(:community).where(status: 'approved', "communities.community_type": 'public')
    end

    @pagy, @posts = pagy(@posts.order(created_at: :desc))

    respond_to do |format|
      format.html
      format.json do
        render json: {
          nextPosts: render_to_string(
            partial: 'shared/posts_preview',
            locals: { posts: @posts, need_icon: true, display_pin: false },
            format: [:html]
          ),
          pagination: view_context.pagy_nav(@pagy)
        }
      end
    end
  end

  def search
    @interests = Interest.includes(:communities, tags: [:taggable]).ransack(params[:q]).result(distinct: true)
    @communities = Community.ransack(params[:q]).result(distinct: true)
  end
end

app/views/home/index.slim
- if user_signed_in? 
  = render partial: "shared/navbar", locals: {community: nil}
- else
  = render partial: "shared/unsigned_navbar"

.min-h-screen.bg-redditGray.pt-28.pb-16 class="dark:bg-gray-900" data-controller="modal pagination" data-action="scroll@window->pagination#scroll"
  .mx-auto.flex.gap-8 class="w-3/4"
    .min-h-screen.flex.flex-col.gap-6 class="w-2/3" data-pagination-target="container"
      = render partial: "shared/post_create_link"

      = render partial: "shared/posts_preview", locals: {posts: @posts, need_icon: true, display_pin: false}

      .flex.justify-center.hidden data-pagination-target="pagination"
        == pagy_nav(@pagy)

    .w-96.flex.flex-col.gap-6
      .w-full.rounded-md.shadow.flex.flex-col.bg-white.overflow-hidden class="dark:bg-gray-700 dark:text-white"
        .home__banner.w-full.h-12.relative 
          .absolute.top-8.left-4.w-14
            = image_pack_tag "media/images/reddit_star.png"
        .pl-20.py-8.text-lg.font-bold
          | Home
        .flex.flex-col.px-3.pb-4.gap-8
          p 
            | Your personal Reddit frontpage. Come here to check in with your favorite communities.
          .flex.flex-col.gap-3
            = link_to "Create Post", new_post_path, class: "py-2 font-sans font-bold text-white rounded-full bg-blue-500 text-center dark:bg-white dark:text-gray-700"
            
            button#community-open class="py-2 font-sans font-bold text-blue-500 rounded-full border border-blue-500 text-center dark:bg-gray-700 dark:text-white dark:border-white" data-action="click->modal#showModal"
              | Create Community
      
      .w-full.rounded-md.shadow.flex.flex-col.bg-white.overflow-hidden.px-3.pt-3.pb-4.gap-2 class="dark:bg-gray-700 dark:text-white"
        .flex.items-center
          .py-2.pl-2.pr-4.text-redditOrange.text-3xl
            i class="fa-solid fa-shield-halved"
          .flex.flex-col 
            strong
              | Reddit premium
            p.text-sm
              | The best Reddit experience, with monthly Coins
        = link_to "Try Now", new_subscription_path, class: "py-2 font-sans font-bold text-white rounded-full bg-redditOrange text-center dark:text-gray-700"
  
  = render partial: "shared/create_community_modal"

- if user_signed_in? && current_user.interests.blank?
  = render partial: "shared/add_interests_modal"

app/views/home/search.slim
- if user_signed_in? 
  = render partial: "shared/navbar", locals: {community: nil}
- else
  = render partial: "shared/unsigned_navbar"

.min-h-screen.bg-redditGray.py-32.flex.flex-col.gap-8 class="dark:bg-gray-900"
  .mx-auto.flex.flex-col.gap-4 class="w-3/5 dark:text-white" 
    strong.text-lg
      |SEARCH BY INTERESTS
    
    - if @interests.blank? 
      .mx-auto.text-lg
        | There is no interest match your search.
    - else
      - @interests.each do |interest| 
        - unless interest.communities.blank?
          .flex.flex-col.gap-4
            strong.text-lg
              = interest.name
            .mx-auto.bg-white.shadow.rounded-sm.flex.flex-col.divide-y.divide-gray-300.w-full class="dark:bg-gray-700 dark:divide-gray-600"
              - interest.communities.each do |community| 
                .w-full.p-4.flex.items-center 
                  = link_to community_path(community), class: "flex items-center" do
                    .h-12.w-12.rounded-full.bg-blue-500.mr-4.overflow-hidden
                      - if community.community_icon.attached?
                        = image_tag community.community_icon, class: "w-full h-full object-cover"
                    .flex.flex-col
                      strong
                        = "/r#{community.name}" 
                      p.text-gray-500 class="dark:text-gray-300"
                        = community.community_type.capitalize
                  
                  - if user_signed_in?
                    = link_to community_users_path(community), class: "ml-auto text-blue-500 font-sans font-bold text-xl bg-blue-100 px-12 py-2 rounded-full dark:bg-gray-600 dark:text-white" do
                      = user_status_in_community(current_user, community)
      

  .mx-auto.flex.flex-col.gap-4 class="w-3/5 dark:text-white" 
    strong.text-lg
      |SEARCH BY COMMUNITIES'S NAME
    
    - if @communities.blank?
      .mx-auto.text-lg 
        | There is no community match your search.
    - else
      .mx-auto.bg-white.shadow.rounded-sm.flex.flex-col.divide-y.divide-gray-300.w-full class="dark:bg-gray-700 dark:divide-gray-600"
        - @communities.each do |community|
          .w-full.p-4.flex.items-center 
            = link_to community_path(community), class: "flex items-center" do
              .h-12.w-12.rounded-full.bg-blue-500.mr-4.overflow-hidden
                - if community.community_icon.attached?
                  = image_tag community.community_icon, class: "w-full h-full object-cover"
              .flex.flex-col
                strong
                  = "/r#{community.name}" 
                p.text-gray-500 class="dark:text-gray-300"
                  = community.community_type.capitalize
            
            - if user_signed_in?
              = link_to community_users_path(community), class: "ml-auto text-blue-500 font-sans font-bold text-xl bg-blue-100 px-12 py-2 rounded-full dark:bg-gray-600 dark:text-white" do
                = user_status_in_community(current_user, community)
          